angular
  .module("gvmItems", [])
  .controller("GvmGalController", function ($scope) {
    $scope.gallery = [      {
        char: "Group",
        charArtSize: "9",
        charArtYear: "2025",
        charArtName: "gvm_char_norm",
        charArtGallery: "porfolioGallery90",
        charArtTitle: "Character Poster",
      },
      {
        char: "Shana",
        charArtSize: "4",
        charArtYear: "2025",
        charArtName: "Shana-Sitting",
        charArtGallery: "porfolioGallery90",
        charArtTitle: "Shana Sitting",
      },
      {
        char: "Shana",
        charArtSize: "4",
        charArtYear: "2025",
        charArtName: "Shana_Sword",
        charArtGallery: "porfolioGallery90",
        charArtTitle: "Shana Sword",
      },
      {
        char: "Seth",
        charArtSize: "4",
        charArtYear: "2025",
        charArtName: "seth-loyalty",
        charArtGallery: "porfolioGallery90",
        charArtTitle: "Seth Loyalty",
      },
      {
        char: "Grandle",
        charArtSize: "3",
        charArtYear: "2025",
        charArtName: "shana-grandle-fin",
        charArtGallery: "porfolioGallery90",
        charArtTitle: "Shana Fin 1",
      },
      {
        char: "Ripper",
        charArtSize: "3",
        charArtYear: "2025",
        charArtName: "shana-ripper-fin",
        charArtGallery: "porfolioGallery90",
        charArtTitle: "Shana Fin 2",
      },
      {
        char: "Ripper",
        charArtSize: "3",
        charArtYear: "2025",
        charArtName: "the_ripper_resting",
        charArtGallery: "porfolioGallery90",
        charArtTitle: "The Ripper Resting",
      },
      {
        char: "Shana",
        charArtSize: "3",
        charArtYear: "2025",
        charArtName: "shana_landing",
        charArtGallery: "porfolioGallery90",
        charArtTitle: "Shana Landing",
      },
      {
        char: "Shana",
        charArtSize: "3",
        charArtYear: "2025",
        charArtName: "shana_defeated",
        charArtGallery: "porfolioGallery90",
        charArtTitle: "Shana Defeated",
      },
      {
        char: "Pond",
        charArtSize: "3",
        charArtYear: "2025",
        charArtName: "pond-profile",
        charArtGallery: "porfolioGallery90",
        charArtTitle: "The Young God Pond",
      },
      {
        char: "Shana",
        charArtSize: "3",
        charArtYear: "2025",
        charArtName: "shana_clarity",
        charArtGallery: "porfolioGallery90",
        charArtTitle: "Shana Clarity",
      },
      {
        char: "Ignis",
        charArtSize: "3",
        charArtYear: "2025",
        charArtName: "Ignisback",
        charArtGallery: "porfolioGallery90",
        charArtTitle: "Ignis Back",
      },
      {
        char: "Grandle",
        charArtSize: "5",
        charArtYear: "2025",
        charArtName: "Golden-grandle",
        charArtGallery: "porfolioGallery90",
        charArtTitle: "Golden Grandle",
      },
      {
        char: "Grandle",
        charArtSize: "8",
        charArtYear: "2025",
        charArtName: "grandle-ignis-faceoff-sm",
        charArtGallery: "porfolioGallery90",
        charArtTitle: "Grandle Ignis Faceoff",
      },
      {
        char: "Ignis",
        charArtSize: "5",
        charArtYear: "2025",
        charArtName: "ignis-faceoff-sm",
        charArtGallery: "porfolioGallery90",
        charArtTitle: "Ignis Faceoff",
      },
      {
        char: "Grandle",
        charArtSize: "5",
        charArtYear: "2025",
        charArtName: "grandle-faceoff-sm",
        charArtGallery: "porfolioGallery90",
        charArtTitle: "Grandle Faceoff",
      },
      {
        char: "Samson",
        charArtSize: "3",
        charArtYear: "2025",
        charArtName: "samson-loyalty-sm",
        charArtGallery: "porfolioGallery90",
        charArtTitle: "Samson Loyalty",
      },
      {
        char: "Shana",
        charArtSize: "3",
        charArtYear: "2025",
        charArtName: "shana-loyalty-sm",
        charArtGallery: "porfolioGallery90",
        charArtTitle: "Shana Loyalty",
      },
      {
        char: "Grandle",
        charArtSize: "3",
        charArtYear: "2025",
        charArtName: "grandle-loss-sm",
        charArtGallery: "porfolioGallery90",
        charArtTitle: "Grandle Loss",
      },
      {
        char: "Shana",
        charArtSize: "3",
        charArtYear: "2025",
        charArtName: "shana-cursed-sm",
        charArtGallery: "porfolioGallery90",
        charArtTitle: "Shana Cursed",
      },
      {
        char: "Grandle",
        charArtSize: "3",
        charArtYear: "2025",
        charArtName: "grandle-fist-sm",
        charArtGallery: "porfolioGallery90",
        charArtTitle: "Grandle Fist",
      },
      {
        char: "Yosh",
        charArtSize: "3",
        charArtYear: "2025",
        charArtName: "yosh-kendo-ready-sm",
        charArtGallery: "porfolioGallery90",
        charArtTitle: "Yosh and Kendo",
      },
      {
        char: "Ignis",
        charArtSize: "3",
        charArtYear: "2025",
        charArtName: "ignis-smile-sm",
        charArtGallery: "porfolioGallery90",
        charArtTitle: "Ignis Smiles",
      },
      {
        char: "Ignis",
        charArtSize: "3",
        charArtYear: "2025",
        charArtName: "grandle-intro-sm",
        charArtGallery: "porfolioGallery90",
        charArtTitle: "Enter the Hero",
      },
    ]
  })
  .controller("GvmController", function ($scope) {
    ($scope.fighters = [
      {
        name: "Chalstolce",
        fullname: "Chalstolce Macabre",
        img: "https://godsvmen.com/img/char/chalstolce_gvm_char.png",
        house: "Dark",
        cityname: "Ottom, Guiresphere",
        city: "https://godsvmen.com/assets/ottom-GVM.png",
        job: "Macabre King",
        style: "Dark Sword Killer",
        weapon: "God Bleeder",
        weaponshot:
          "https://godsvmen.com/swordsayers/img/chalstolce-weapon.png",
        special: "Dark Fury",
        personality: "Vile",
        actionshot: "Bleeding Cut",
        actionshotlink: "https://godsvmen.com/swordsayers/img/Kendo-full.png",
        gallery: "1",
        filter: "ottom",
      },
      {
        name: "Crin",
        fullname: "Crin Robinson",
        img: "https://godsvmen.com/img/char/crin_gvm_char.png",
        house: "Robe",
        cityname: "Abya Yala, Jupiter",
        city: "https://godsvmen.com/assets/jupiter-GVM.png",
        job: "Robe King",
        style: "Light of Hope",
        weapon: "Star Dusk",
        weaponshot: "https://godsvmen.com/swordsayers/img/crin-weapon.png",
        special: "Lit Fury",
        personality: "Stoic",
        actionshot: "Sword Mastery",
        actionshotlink: "https://godsvmen.com/swordsayers/img/Kendo-full.png",
        gallery: "2",
        filter: "ab",
      },
      {
        name: "Lem",
        fullname: "Lem Bevin",
        img: "https://godsvmen.com/img/char/lem_gvm_char.png",
        house: "Wolf",
        cityname: "Lune, Kreis",
        city: "https://godsvmen.com/assets/lune-GVM.png",
        job: "Wolf King",
        style: "Hard Claws",
        weapon: "Basilisk",
        weaponshot: "https://godsvmen.com/swordsayers/img/lem-weapon.png",
        special: "Time Stop",
        personality: "Nervous",
        actionshot: "Wolf Duo",
        actionshotlink: "https://godsvmen.com/swordsayers/img/Kendo-full.png",
        gallery: "3",
        filter: "kreis",
      },
      {
        name: "Yosh",
        fullname: "Yosh Baskerville",
        img: "https://godsvmen.com/img/char/yosh_gvm_char.png",
        house: "Robe",
        cityname: "Abya Yala, Jupiter",
        city: "https://godsvmen.com/assets/jupiter-GVM.png",
        job: "Robe Knight",
        style: "Slicer",
        weapon: "Rhetoric",
        weaponshot: "https://godsvmen.com/swordsayers/img/yosh-weapon.png",
        special: "The Answer",
        personality: "Cautious",
        actionshot: "The Robe Slayer",
        actionshotlink: "https://godsvmen.com/swordsayers/img/Yosh-Full.png",
        bio: "https://godsvmen.com/characters/yosh.html",
        gallery: "4",
        filter: "ab",
      },
      {
        name: "Samson",
        fullname: "Samson",
        img: "https://godsvmen.com/img/char/samson_gvm_char.png",
        house: "None",
        cityname: "Unknown",
        city: "https://godsvmen.com/assets/unknown-GVM.png",
        job: "Boulevard Fighter",
        style: "Dicer",
        weapon: "Y-Calibre",
        weaponshot: "https://godsvmen.com/swordsayers/img/samson-weapon.png",
        special: "Y Knot",
        personality: "Bold",
        actionshot: "Y Slicer",
        actionshotlink: "https://godsvmen.com/swordsayers/img/Samson-full.png",
        bio: "https://godsvmen.com/characters/samson.html",
        gallery: "5",
        filter: "u",
      },
      {
        name: "Grandle",
        fullname: "Grandle Robinson",
        img: "https://godsvmen.com/img/char/grandle_gvm_char.png",
        house: "Robe",
        cityname: "Abya Yala, Jupiter",
        city: "https://godsvmen.com/assets/jupiter-GVM.png",
        job: "Robe Prince",
        style: "Gunner",
        weapon: "9mm Handguns",
        weaponshot: "https://godsvmen.com/swordsayers/img/grandle-weapon.png",
        special: "Robe Ammo",
        personality: "Cocky",
        actionshot: "Chimera Punch",
        actionshotlink: "https://godsvmen.com/swordsayers/img/Grandle-full.png",
        bio: "https://godsvmen.com/characters/grandle.html",
        gallery: "6",
        filter: "ab",
      },
      {
        name: "Shana",
        fullname: "Shana Robinson",
        img: "https://godsvmen.com/img/char/shana_gvm_char.png",
        house: "Robe",
        cityname: "Abya Yala, Jupiter",
        city: "https://godsvmen.com/assets/jupiter-GVM.png",
        job: "Robe General",
        style: "Slicer",
        weapon: "Robin",
        weaponshot: "https://godsvmen.com/swordsayers/img/shana-weapon.png",
        special: "Robe Final",
        personality: "Confident",
        actionshot: "Slash Redux",
        actionshotlink: "https://godsvmen.com/swordsayers/img/Shana-full.png",
        bio: "https://godsvmen.com/characters/shana.html",
        gallery: "7",
        filter: "ab",
      },
      //        {
      //          name: 'Robe',
      //          fullname: 'Robe Knight',
      //          img: 'https://godsvmen.com/img/char/robe_knight_gvm_char.png',
      //          house: 'Robe',
      //          cityname: 'Abya Yala, Jupiter',
      //          city: 'https://godsvmen.com/assets/jupiter-GVM.png',
      //          job: 'Robe Swordsman',
      //          style: 'Slicer',
      //          weapon: 'Dual Swords',
      //          weaponshot: 'https://godsvmen.com/swordsayers/img/grandle-weapon.png',
      //          special: 'Last Fury',
      //          personality: 'Confident',
      //          actionshot: 'Robe Decider',
      //          actionshotlink: 'https://godsvmen.com/swordsayers/img/Robe-Knight-Full.png',
      //          gallery: '6',
      //          filter: 'ab'
      //        },
      //		{
      //          name: 'Franker',
      //          fullname: 'Franker Moon',
      //          img: 'https://godsvmen.com/img/char/franker_gvm_char.png',
      //          house: 'Goth',
      //          cityname: 'Vortex, Gradiis',
      //          city: 'https://godsvmen.com/assets/jupiter-GVM.png',
      //          job: 'Swift Gutter',
      //          style: 'Sword Breaker',
      //          weapon: 'Long Ax',
      //          weaponshot: 'https://godsvmen.com/swordsayers/img/grandle-weapon.png',
      //          special: 'Thrice Cut',
      //          personality: 'Motivated',
      //          actionshot: 'Ax Fury',
      //          actionshotlink: 'https://godsvmen.com/swordsayers/img/Franker-Full.png',
      //          gallery: '665',
      //          filter: 'grad'
      //        },
      {
        name: "Christopher",
        fullname: "Christopher",
        img: "https://godsvmen.com/img/char/chris_gvm_char.png",
        house: "None",
        cityname: "Unknown",
        city: "https://godsvmen.com/assets/unknown-GVM.png",
        job: "Boulevard Fighter",
        style: "Brawler",
        weapon: "Gloves",
        weaponshot:
          "https://godsvmen.com/swordsayers/img/christopher-weapon.png",
        special: "Dream Punch",
        personality: "Quiet",
        actionshot: "Brute Force",
        actionshotlink: "https://godsvmen.com/swordsayers/img/Kendo-full.png",
        bio: "https://godsvmen.com/characters/chris.html",
        gallery: "8",
        filter: "u",
      },
      {
        name: "Seth",
        fullname: "Seth Gate",
        img: "https://godsvmen.com/img/char/seth_gvm_char.png",
        house: "None",
        cityname: "Unknown",
        city: "https://godsvmen.com/assets/unknown-GVM.png",
        job: "Olan Soldier",
        style: "Chopper",
        weapon: "Ax",
        weaponshot: "https://godsvmen.com/swordsayers/img/seth-weapon.png",
        special: "Crossover",
        personality: "Proud",
        actionshot: "Cross Ax Olan",
        actionshotlink: "https://godsvmen.com/swordsayers/img/Kendo-full.png",
        gallery: "9",
        filter: "u",
      },
      {
        name: "Flow",
        fullname: "Flow Macabre",
        img: "https://godsvmen.com/img/char/flow_gvm_char.png",
        house: "Dark",
        cityname: "Ottom, Guiresphere",
        city: "https://godsvmen.com/assets/ottom-GVM.png",
        job: "Dark General",
        style: "Slayer",
        weapon: "Knives",
        weaponshot: "https://godsvmen.com/swordsayers/img/flow-weapon.png",
        special: "Lights Out",
        personality: "Focused",
        actionshot: "Flower's Thorns",
        actionshotlink: "https://godsvmen.com/swordsayers/img/Flower-full.png",
        bio: "https://godsvmen.com/characters/flow.html",
        gallery: "10",
        filter: "ottom",
      },
      {
        name: "Ripper",
        fullname: "Kendo the Ripper",
        img: "https://godsvmen.com/img/char/ripper_gvm_char.png",
        house: "None",
        cityname: "Unknown",
        city: "https://godsvmen.com/assets/unknown-GVM.png",
        job: "Prisoner",
        style: "Mace Demon",
        weapon: "Ball and Chains",
        weaponshot: "https://godsvmen.com/swordsayers/img/kendo-weapon.png",
        special: "Choker",
        personality: "Erradic",
        actionshot: "Kendo’s Chains",
        actionshotlink: "https://godsvmen.com/swordsayers/img/Kendo-full.png",
        gallery: "11",
        filter: "u",
      },
      {
        name: "Delila",
        fullname: "Delila Gida",
        img: "https://godsvmen.com/img/char/delila_gvm_char.png",
        house: "None",
        cityname: "Lore, Lords",
        city: "https://godsvmen.com/assets/lore-GVM.png",
        job: "Rebel Leader",
        style: "Big Sword",
        weapon: "Heartless",
        weaponshot: "https://godsvmen.com/swordsayers/img/Delila-full.png",
        special: "Beguile",
        personality: "Indifferent",
        actionshot: "Rebel's Blade",
        actionshotlink: "https://godsvmen.com/swordsayers/img/Delila-full.png",
        gallery: "12",
        filter: "lords",
      },
      {
        name: "Pond",
        fullname: "Pond",
        img: "https://godsvmen.com/img/char/pond_gvm_char.png",
        house: "Hanor",
        cityname: "Hanor, Heaven's Edge",
        city: "https://godsvmen.com/assets/hanor-GVM.png",
        job: "The Young God",
        style: "God Kicks",
        weapon: "First Arrow",
        weaponshot: "",
        special: "Halo Breach",
        personality: "Cheerful",
        actionshot: "Soul End",
        actionshotlink: "https://godsvmen.com/swordsayers/img/Pond-full.png",
        gallery: "13",
        filter: "hanor",
      },
      //		{
      //          name: 'Macabre Soldier',
      //          fullname: 'Macabre Soldier',
      //          img: 'https://godsvmen.com/img/char/mac_knight_gvm_char.png',
      //          house: 'Dark',
      //          cityname: 'Ottom, Guiresphere',
      //          city: 'https://godsvmen.com/assets/ottom-GVM.png',
      //          job: 'Gunner',
      //          style: 'Gunner Swordsmen',
      //          weapon: 'Dual Swords',
      //          weaponshot: 'https://godsvmen.com/swordsayers/img/chalstolce-weapon.png',
      //          special: 'Dark Punishment',
      //          personality: 'Nervous',
      //          actionshot: 'Gun Slice',
      //          actionshotlink: 'https://godsvmen.com/swordsayers/img/Mac_Knight_full.png',
      //          gallery: '111',
      //          filter: 'ottom'
      //        },
      //        {
      //          name: 'Volcanis',
      //          fullname: 'Volcanis',
      //          img: 'https://godsvmen.com/img/char/volcanis_gvm_char.png',
      //          house: 'Hanor',
      //          cityname: 'Hanor, Heaven\'s Edge',
      //          city: 'https://godsvmen.com/assets/hanor-GVM.png',
      //          job: 'The Old God',
      //          style: 'God Palm',
      //          weapon: 'Flame Edge',
      //          weaponshot: '',
      //          special: 'God Strike',
      //          personality: 'Manipulative',
      //          actionshot: 'Heart of Flames',
      //          actionshotlink: 'https://godsvmen.com/swordsayers/img/Volcanis-full.png',
      //          gallery: '14',
      //          filter: 'hanor'
      //        },
      //        {
      //          name: 'Mouse',
      //          fullname: 'Ichabod Zanzbo',
      //          img: 'https://godsvmen.com/img/char/mouse_gvm_char.png',
      //          house: 'Weber',
      //          cityname: 'Lore, Lords',
      //          city: 'https://godsvmen.com/assets/lore-GVM.png',
      //          job: 'Olan Soldier',
      //          style: 'Long Bo',
      //          weapon: 'Bo',
      //          weaponshot: '',
      //          special: 'Striker Shot',
      //          personality: 'Eager',
      //          actionshot: 'Sonic Strike',
      //          actionshotlink: 'https://godsvmen.com/swordsayers/img/Mouse-Full.png',
      //          gallery: '151',
      //          filter: 'lords'
      //        },
      //        {
      //          name: 'Lit',
      //          fullname: 'Lit Knight',
      //          img: 'https://godsvmen.com/img/char/lit_gvm_char.png',
      //          house: 'Weber',
      //          cityname: 'Lore, Lords',
      //          city: 'https://godsvmen.com/assets/lore-GVM.png',
      //          job: 'Sword Mage',
      //          style: 'Magic Sword',
      //          weapon: 'Sword & Dagger',
      //          weaponshot: '',
      //          special: '100 Slashes',
      //          personality: 'Playful',
      //          actionshot: 'Perfect Pose',
      //          actionshotlink: 'https://godsvmen.com/swordsayers/img/Lit-full.png',
      //          gallery: '200',
      //          filter: 'lords'
      //        },
      //		{
      //          name: 'Wolf Soldier',
      //          fullname: 'Lunar Solider',
      //          img: 'https://godsvmen.com/img/char/wolf_knight_gvm_char.png',
      //          house: 'Wolf',
      //          cityname: 'Lune, Kreis',
      //          city: 'https://godsvmen.com/assets/lune-GVM.png',
      //          job: 'Werewolf',
      //          style: 'Hard Claws',
      //          weapon: 'Claw Hook',
      //          weaponshot: 'https://godsvmen.com/swordsayers/img/lem-weapon.png',
      //          special: 'Chronos Punch',
      //          personality: 'Angry',
      //          actionshot: 'Were Dive',
      //          actionshotlink: 'https://godsvmen.com/swordsayers/img/Lunar-full.png',
      //          gallery: '3',
      //          filter: 'kreis sold'
      //        },
      {
        name: "Ignis",
        fullname: "Ignis Weber",
        img: "https://godsvmen.com/img/char/ignis_gvm_char.png",
        house: "Weber",
        cityname: "Lore, Lords",
        city: "https://godsvmen.com/assets/lore-GVM.png",
        job: "The Weber Prince",
        style: "Devil Fists",
        weapon: "Hand of Hell",
        weaponshot: "",
        special: "Morne",
        personality: "Calculating",
        actionshot: "Demonic Punch",
        actionshotlink: "https://godsvmen.com/swordsayers/img/Kendo-full.png",
        gallery: "155",
        filter: "lords",
      },
      {
        name: "Taur",
        fullname: "Taur Weber",
        img: "https://godsvmen.com/img/char/taur_gvm_char.png",
        house: "Weber",
        cityname: "Lore, Lords",
        city: "https://godsvmen.com/assets/lore-GVM.png",
        job: "Weber Queen",
        style: "Mag Fang",
        weapon: "Venga",
        weaponshot: "https://godsvmen.com/swordsayers/img/taur-weapon.png",
        special: "Mag Stop",
        personality: "Loyal",
        actionshot: "Force",
        actionshotlink: "https://godsvmen.com/swordsayers/img/Kendo-full.png",
        gallery: "166",
        filter: "lords",
      },
      {
        name: "Sol",
        fullname: "Sol Weber",
        img: "https://godsvmen.com/img/char/sol_gvm_char.png",
        house: "Weber",
        cityname: "Lore, Lords",
        city: "https://godsvmen.com/assets/lore-GVM.png",
        job: "The AllKing",
        style: "God Fists",
        weapon: "Hand of God",
        weaponshot: "",
        special: "Cry",
        personality: "Stubborn",
        actionshot: "G.O.D.",
        actionshotlink: "https://godsvmen.com/swordsayers/img/Kendo-full.png",
        gallery: "17",
        filter: "lords",
      },
    ]),
      ($scope.ofighters = [
        {
          name: "Yosh",
          fullname: "Yosh Baskerville",
          img: "https://godsvmen.com/img/char/yosh_gvm_char.png",
          house: "Robe",
          cityname: "Abya Yala, Jupiter",
          city: "https://godsvmen.com/assets/jupiter-GVM.png",
          job: "Robe Knight",
          style: "Slicer",
          weapon: "Rhetoric",
          weaponshot: "https://godsvmen.com/swordsayers/img/yosh-weapon.png",
          special: "The Answer",
          personality: "Cautious",
          actionshot: "Robe Glory",
          actionshotlink: "https://godsvmen.com/swordsayers/img/YoshVMouse.png",
          bio: "https://godsvmen.com/characters/yosh.html",
          gallery: "4",
          filter: "ab",
        },
        {
          name: "Samson",
          fullname: "Samson",
          img: "https://godsvmen.com/img/char/samson_gvm_char.png",
          house: "None",
          cityname: "Unknown",
          city: "https://godsvmen.com/assets/unknown-GVM.png",
          job: "Boulevard Fighter",
          style: "Dicer",
          weapon: "Y-Calibre",
          weaponshot: "https://godsvmen.com/swordsayers/img/samson-weapon.png",
          special: "Y Knot",
          personality: "Bold",
          actionshot: "Y Slicer",
          actionshotlink:
            "https://godsvmen.com/swordsayers/img/SamsonVVoorhies.png",
          bio: "https://godsvmen.com/characters/samson.html",
          gallery: "5",
          filter: "u",
        },
        {
          name: "Grandle",
          fullname: "Grandle Robinson",
          img: "https://godsvmen.com/img/char/grandle_gvm_char.png",
          house: "Robe",
          cityname: "Abya Yala, Jupiter",
          city: "https://godsvmen.com/assets/jupiter-GVM.png",
          job: "Robe Prince",
          style: "Gunner",
          weapon: "9mm Handguns",
          weaponshot: "https://godsvmen.com/swordsayers/img/grandle-weapon.png",
          special: "Robe Ammo",
          personality: "Cocky",
          actionshot: "Golden Punch",
          actionshotlink:
            "https://godsvmen.com/swordsayers/img/GrandleVRobe.png",
          bio: "https://godsvmen.com/characters/grandle.html",
          gallery: "6",
          filter: "ab",
        },
        {
          name: "Shana",
          fullname: "Shana Robinson",
          img: "https://godsvmen.com/img/char/shana_gvm_char.png",
          house: "Robe",
          cityname: "Abya Yala, Jupiter",
          city: "https://godsvmen.com/assets/jupiter-GVM.png",
          job: "Robe General",
          style: "Slicer",
          weapon: "Robin",
          weaponshot: "https://godsvmen.com/swordsayers/img/shana-weapon.png",
          special: "Robe Final",
          personality: "Confident",
          actionshot: "Slash Redux",
          actionshotlink:
            "https://godsvmen.com/swordsayers/img/VolcanisVShana.png",
          bio: "https://godsvmen.com/characters/shana.html",
          gallery: "7",
          filter: "ab",
        },
        {
          name: "Robe",
          fullname: "Robe Knight",
          img: "https://godsvmen.com/img/char/robe_knight_gvm_char.png",
          house: "Robe",
          cityname: "Abya Yala, Jupiter",
          city: "https://godsvmen.com/assets/jupiter-GVM.png",
          job: "Robe Swordsman",
          style: "Slicer",
          weapon: "Dual Swords",
          weaponshot: "https://godsvmen.com/swordsayers/img/grandle-weapon.png",
          special: "Last Fury",
          personality: "Confident",
          actionshot: "Robe Decider",
          actionshotlink:
            "https://godsvmen.com/swordsayers/img/GrandleVRobe.png",
          bio: "https://godsvmen.com/characters/robe.html",
          gallery: "6",
          filter: "ab",
        },
        {
          name: "Christopher",
          fullname: "Christopher",
          img: "https://godsvmen.com/img/char/chris_gvm_char.png",
          house: "None",
          cityname: "Unknown",
          city: "https://godsvmen.com/assets/unknown-GVM.png",
          job: "Boulevard Fighter",
          style: "Brawler",
          weapon: "Gloves",
          weaponshot:
            "https://godsvmen.com/swordsayers/img/christopher-weapon.png",
          special: "Dream Punch",
          personality: "Quiet",
          actionshot: "Brute Force",
          actionshotlink:
            "https://godsvmen.com/swordsayers/img/ChrisVSordin.png",
          bio: "https://godsvmen.com/characters/chris.html",
          gallery: "8",
          filter: "u",
        },
        {
          name: "Seth",
          fullname: "Seth Gate",
          img: "https://godsvmen.com/img/char/seth_gvm_char.png",
          house: "None",
          cityname: "Unknown",
          city: "https://godsvmen.com/assets/unknown-GVM.png",
          job: "Olan Soldier",
          style: "Chopper",
          weapon: "Ax",
          weaponshot: "https://godsvmen.com/swordsayers/img/seth-weapon.png",
          special: "Crossover",
          personality: "Proud",
          actionshot: "Cross Ax Olan",
          actionshotlink:
            "https://godsvmen.com/swordsayers/img/FrankerVSeth.png",
          bio: "https://godsvmen.com/characters/seth.html",
          gallery: "9",
          filter: "u",
        },
        {
          name: "Flow",
          fullname: "Flow Macabre",
          img: "https://godsvmen.com/img/char/flow_gvm_char.png",
          house: "Dark",
          cityname: "Ottom, Guiresphere",
          city: "https://godsvmen.com/assets/ottom-GVM.png",
          job: "Dark General",
          style: "Slayer",
          weapon: "Knives",
          weaponshot: "https://godsvmen.com/swordsayers/img/flow-weapon.png",
          special: "Lights Out",
          personality: "Focused",
          actionshot: "Flower's Thorns",
          actionshotlink:
            "https://godsvmen.com/swordsayers/img/Macabre_KnightVFlower.png",
          bio: "https://godsvmen.com/characters/flow.html",
          gallery: "10",
          filter: "ottom",
        },
        {
          name: "Ripper",
          fullname: "Kendo the Ripper",
          img: "https://godsvmen.com/img/char/ripper_gvm_char.png",
          house: "None",
          cityname: "Unknown",
          city: "https://godsvmen.com/assets/unknown-GVM.png",
          job: "Prisoner",
          style: "Mace Demon",
          weapon: "Ball and Chains",
          weaponshot: "https://godsvmen.com/swordsayers/img/kendo-weapon.png",
          special: "Choker",
          personality: "Erradic",
          actionshot: "Kendo’s Chains",
          actionshotlink:
            "https://godsvmen.com/swordsayers/img/SparrowVKendo.png",
          bio: "https://godsvmen.com/characters/ripper.html",
          gallery: "11",
          filter: "u",
        },
        {
          name: "Delila",
          fullname: "Delila Gida",
          img: "https://godsvmen.com/img/char/delila_gvm_char.png",
          house: "None",
          cityname: "Lore, Lords",
          city: "https://godsvmen.com/assets/lore-GVM.png",
          job: "Rebel Leader",
          style: "Big Sword",
          weapon: "Heartless",
          weaponshot: "https://godsvmen.com/swordsayers/img/Delila-full.png",
          special: "Beguile",
          personality: "Indifferent",
          actionshot: "Rebel's Blade",
          actionshotlink:
            "https://godsvmen.com/swordsayers/img/PondVDelila.png",
          bio: "https://godsvmen.com/characters/delila.html",
          gallery: "12",
          filter: "lords",
        },
        {
          name: "Eln-Delila",
          fullname: "Eln-Delila",
          img: "https://godsvmen.com/img/char/eln-delila_gvm_char.png",
          house: "None",
          cityname: "Lore, Lords",
          city: "https://godsvmen.com/assets/lore-GVM.png",
          job: "Eln Soldier",
          style: "Big Sword",
          weapon: "Heartless",
          weaponshot:
            "https://godsvmen.com/swordsayers/img/Eln-Delila-full.png",
          special: "Beguile",
          personality: "Furious",
          actionshot: "Rebel's Blade",
          actionshotlink:
            "https://godsvmen.com/swordsayers/img/Eln-Delila-full.png",
          bio: "https://godsvmen.com/characters/eln-delila.html",
          gallery: "120",
          filter: "lords",
        },
        {
          name: "Bruno",
          fullname: "Bruno Moon",
          img: "https://godsvmen.com/img/char/bruno_gvm_char.png",
          house: "Goth",
          cityname: "Vortex, Gradiis",
          city: "https://godsvmen.com/assets/vortex-GVM.png",
          job: "Goth Leader",
          style: "Earth Breaker",
          weapon: "Demons",
          //          weaponshot: 'https://godsvmen.com/swordsayers/img/grandle-weapon.png',
          special: "Massive",
          personality: "Obsessed",
          actionshot: "Evil Surge",
          actionshotlink:
            "https://godsvmen.com/swordsayers/img/QuintVBruno.png",
          bio: "https://godsvmen.com/characters/bruno.html",
          gallery: "660",
          filter: "grad",
        },
        {
          name: "Franker",
          fullname: "Franker Moon",
          img: "https://godsvmen.com/img/char/franker_gvm_char.png",
          house: "Goth",
          cityname: "Vortex, Gradiis",
          city: "https://godsvmen.com/assets/vortex-GVM.png",
          job: "Swift Gutter",
          style: "Sword Breaker",
          weapon: "Long Ax",
          weaponshot: "https://godsvmen.com/swordsayers/img/grandle-weapon.png",
          special: "Thrice Cut",
          personality: "Motivated",
          actionshot: "Ax Fury",
          actionshotlink:
            "https://godsvmen.com/swordsayers/img/FrankerVSeth.png",
          bio: "https://godsvmen.com/characters/franker.html",
          gallery: "665",
          filter: "grad",
        },
        {
          name: "Tyree",
          fullname: "Tyree Toth",
          img: "https://godsvmen.com/img/char/toth_gvm_char.png",
          house: "Goth",
          cityname: "Vortex, Gradiis",
          city: "https://godsvmen.com/assets/vortex-GVM.png",
          job: "Demon Hunter",
          style: "Large Smash",
          weapon: "Big Hammer",
          weaponshot: "https://godsvmen.com/swordsayers/img/grandle-weapon.png",
          special: "Masher",
          personality: "Serious",
          actionshot: "Super Masher",
          actionshotlink:
            "https://godsvmen.com/swordsayers/img/DemoniVToth.png",
          bio: "https://godsvmen.com/characters/toth.html",
          gallery: "664",
          filter: "grad",
        },
        {
          name: "Sparrow",
          fullname: "Sparrow Wilkerson",
          img: "https://godsvmen.com/img/char/sparrow_gvm_char.png",
          house: "None",
          cityname: "Abya Yala, Jupiter",
          city: "https://godsvmen.com/assets/unknown-GVM.png",
          job: "Demon Hunter",
          style: "Brute",
          weapon: "Holis",
          weaponshot: "https://godsvmen.com/swordsayers/img/shana-weapon.png",
          special: "Demon Rig",
          personality: "Unmoving",
          actionshot: "Sparrow's Wing",
          actionshotlink:
            "https://godsvmen.com/swordsayers/img/SparrowVKendo.png",
          bio: "https://godsvmen.com/characters/sparrow.html",
          gallery: "7",
          filter: "u",
        },
        {
          name: "Voorhies",
          fullname: "Voorhies Direside",
          img: "https://godsvmen.com/img/char/voorhies_gvm_char.png",
          house: "Mastery",
          cityname: "Abya Yala, Jupiter",
          city: "https://godsvmen.com/assets/jupiter-GVM.png",
          job: "Mastery Disciple",
          style: "Carver",
          weapon: "Red Sword",
          weaponshot:
            "https://godsvmen.com/swordsayers/img/voorhies-weapon.png",
          special: "Robe Final",
          personality: "Sleek",
          actionshot: "Blood Drainer",
          actionshotlink:
            "https://godsvmen.com/swordsayers/img/SamsonVVoorhies.png",
          bio: "https://godsvmen.com/characters/voorhies.html",
          gallery: "7",
          filter: "ab",
        },
        {
          name: "Pond",
          fullname: "Pond",
          img: "https://godsvmen.com/img/char/pond_gvm_char.png",
          house: "Hanor",
          cityname: "Hanor, Heaven's Edge",
          city: "https://godsvmen.com/assets/hanor-GVM.png",
          job: "The Young God",
          style: "God Kicks",
          weapon: "First Arrow",
          weaponshot: "",
          special: "Halo Breach",
          personality: "Cheerful",
          actionshot: "Soul End",
          actionshotlink:
            "https://godsvmen.com/swordsayers/img/PondVDelila.png",
          bio: "https://godsvmen.com/characters/pond.html",
          gallery: "13",
          filter: "hanor",
        },
        {
          name: "Sordin",
          fullname: "Sordin",
          img: "https://godsvmen.com/img/char/sordin_gvm_char.png",
          house: "Hanor",
          cityname: "Hanor, Heaven's Edge",
          city: "https://godsvmen.com/assets/hanor-GVM.png",
          job: "The Plump Knight",
          style: "Ham Hands",
          weapon: "Needle Point",
          weaponshot: "",
          special: "Hard Castle",
          personality: "Fortified",
          actionshot: "Bleak Reaper",
          actionshotlink:
            "https://godsvmen.com/swordsayers/img/ChrisVSordin.png",
          bio: "https://godsvmen.com/characters/sordin.html",
          gallery: "13",
          filter: "hanor",
        },
        {
          name: "Demoni",
          fullname: "Larnx Demoni",
          img: "https://godsvmen.com/img/char/demoni_gvm_char.png",
          house: "None",
          cityname: "Unknown",
          city: "https://godsvmen.com/assets/unknown-GVM.png",
          job: "The Demon Lord",
          style: "Enormous Slices",
          weapon: "Giant Scythe",
          weaponshot: "",
          special: "Dark Hallows",
          personality: "Fevered",
          actionshot: "Soul Null",
          actionshotlink:
            "https://godsvmen.com/swordsayers/img/DemoniVToth.png",
          bio: "https://godsvmen.com/characters/demoni.html",
          gallery: "13",
          filter: "u",
        },
        {
          name: "Macabre Soldier",
          fullname: "Macabre Soldier",
          img: "https://godsvmen.com/img/char/mac_knight_gvm_char.png",
          house: "Dark",
          cityname: "Ottom, Guiresphere",
          city: "https://godsvmen.com/assets/ottom-GVM.png",
          job: "Gunner",
          style: "Gunner Swordsmen",
          weapon: "Dual Swords",
          weaponshot:
            "https://godsvmen.com/swordsayers/img/chalstolce-weapon.png",
          special: "Dark Punishment",
          personality: "Nervous",
          actionshot: "Gun Slice",
          actionshotlink:
            "https://godsvmen.com/swordsayers/img/Macabre_KnightVFlower.png",
          bio: "https://godsvmen.com/characters/macabre-knight.html",
          gallery: "111",
          filter: "ottom",
        },
        {
          name: "Volcanis",
          fullname: "Volcanis",
          img: "https://godsvmen.com/img/char/volcanis_gvm_char.png",
          house: "Hanor",
          cityname: "Hanor, Heaven's Edge",
          city: "https://godsvmen.com/assets/hanor-GVM.png",
          job: "The Old God",
          style: "God Palm",
          weapon: "Flame Edge",
          weaponshot: "",
          special: "God Strike",
          personality: "Manipulative",
          actionshot: "Heart of Flames",
          actionshotlink:
            "https://godsvmen.com/swordsayers/img/VolcanisVShana.png",
          bio: "https://godsvmen.com/characters/volcanis.html",
          gallery: "14",
          filter: "hanor",
        },
        {
          name: "Mouse",
          fullname: "Ichabod Zanzbo",
          img: "https://godsvmen.com/img/char/mouse_gvm_char.png",
          house: "Weber",
          cityname: "Lore, Lords",
          city: "https://godsvmen.com/assets/lore-GVM.png",
          job: "Olan Soldier",
          style: "Long Bo",
          weapon: "Bo",
          weaponshot: "",
          special: "Striker Shot",
          personality: "Eager",
          actionshot: "Bo Strike",
          actionshotlink: "https://godsvmen.com/swordsayers/img/YoshVMouse.png",
          bio: "https://godsvmen.com/characters/mouse.html",
          gallery: "151",
          filter: "lords",
        },
        {
          name: "Stormheart",
          fullname: "Stormheart",
          img: "https://godsvmen.com/img/char/stormheart_gvm_char.png",
          house: "None",
          cityname: "Unknown",
          city: "https://godsvmen.com/assets/unknown-GVM.png",
          job: "The Far Killer",
          style: "Time Sword",
          weapon: "One Handed Saw",
          weaponshot: "",
          special: "Tremor Slice",
          personality: "Dedicated",
          actionshot: "Seconds",
          actionshotlink:
            "https://godsvmen.com/swordsayers/img/IgnisVStormheart.png",
          bio: "https://godsvmen.com/characters/stormheart.html",
          gallery: "13",
          filter: "u",
        },
        {
          name: "Lit",
          fullname: "Lit Knight",
          img: "https://godsvmen.com/img/char/lit_gvm_char.png",
          house: "Weber",
          cityname: "Lore, Lords",
          city: "https://godsvmen.com/assets/lore-GVM.png",
          job: "Sword Mage",
          style: "Magic Sword",
          weapon: "Sword & Dagger",
          weaponshot: "",
          special: "100 Slashes",
          personality: "Playful",
          actionshot: "Perfect Pose",
          actionshotlink: "https://godsvmen.com/swordsayers/img/LitVLunar.png",
          bio: "https://godsvmen.com/characters/lit-knight.html",
          gallery: "200",
          filter: "lords",
        },
        {
          name: "Wolf Soldier",
          fullname: "Lunar Solider",
          img: "https://godsvmen.com/img/char/wolf_knight_gvm_char.png",
          house: "Wolf",
          cityname: "Lune, Kreis",
          city: "https://godsvmen.com/assets/lune-GVM.png",
          job: "Werewolf",
          style: "Hard Claws",
          weapon: "Claw Hook",
          weaponshot: "https://godsvmen.com/swordsayers/img/lem-weapon.png",
          special: "Chronos Punch",
          personality: "Angry",
          actionshot: "Were Dive",
          actionshotlink: "https://godsvmen.com/swordsayers/img/LitVLunar.png",
          bio: "https://godsvmen.com/characters/lunar-knight.html",
          gallery: "3",
          filter: "kreis sold",
        },
        {
          name: "Lars",
          fullname: "Lars",
          img: "https://godsvmen.com/img/char/lars_gvm_char.png",
          house: "Wolf",
          cityname: "Lune, Kreis",
          city: "https://godsvmen.com/assets/lune-GVM.png",
          job: "Werewolf",
          style: "Hard Claws",
          weapon: "Claw Hook",
          weaponshot: "https://godsvmen.com/swordsayers/img/lem-weapon.png",
          special: "Chronos Punch",
          personality: "Angry",
          actionshot: "Were Dive",
          actionshotlink:
            "https://godsvmen.com/swordsayers/img/LarsVMaxither.png",
          bio: "https://godsvmen.com/characters/lars.html",
          gallery: "3",
          filter: "kreis sold",
        },
        {
          name: "Fara",
          fullname: "Fara Fontaine",
          img: "https://godsvmen.com/img/char/fara_gvm_char.png",
          house: "Goth",
          cityname: "Vortex, Gradiis",
          city: "https://godsvmen.com/assets/vortex-GVM.png",
          job: "Celebrity Fighter",
          style: "Star Smash",
          weapon: "Diamond Claws",
          weaponshot: "https://godsvmen.com/swordsayers/img/fara-weapon.png",
          special: "Mincer",
          personality: "Glam",
          actionshot: "Super Smasher",
          actionshotlink:
            "https://godsvmen.com/swordsayers/img/BastionVFara.png",
          bio: "https://godsvmen.com/characters/fara.html",
          gallery: "669",
          filter: "grad",
        },
        {
          name: "Quint",
          fullname: "Quint",
          img: "https://godsvmen.com/img/char/quint_gvm_char.png",
          house: "None",
          cityname: "Lune, Kreis",
          city: "https://godsvmen.com/assets/lune-GVM.png",
          job: "Relaxed Fighter",
          style: "Hard Hitting",
          weapon: "Fists and Feet",
          //          weaponshot: 'https://godsvmen.com/swordsayers/img/lem-weapon.png',
          special: "Zu Kicks",
          personality: "Relaxed",
          actionshot: "Round House",
          actionshotlink:
            "https://godsvmen.com/swordsayers/img/QuintVBruno.png",
          bio: "https://godsvmen.com/characters/quint.html",
          gallery: "333",
          filter: "kreis sold",
        },
        {
          name: "Tesha",
          fullname: "Tesha",
          img: "https://godsvmen.com/img/char/tesha_gvm_char.png",
          house: "None",
          cityname: "Lune, Kreis",
          city: "https://godsvmen.com/assets/lune-GVM.png",
          job: "Mad Merchant",
          style: "Items",
          weapon: "Hammer and Feet",
          special: "Discount",
          personality: "Angry",
          actionshot: "Hammer Time",
          actionshotlink:
            "https://godsvmen.com/swordsayers/img/TeshaVEln-Delila.png",
          bio: "https://godsvmen.com/characters/tesha.html",
          gallery: "330",
          filter: "kreis sold",
        },
        {
          name: "Bastion",
          fullname: "Bastion",
          img: "https://godsvmen.com/img/char/bastion_gvm_char.png",
          house: "None",
          cityname: "Lune, Kreis",
          city: "https://godsvmen.com/assets/lune-GVM.png",
          job: "Lion Exile",
          style: "Cutting",
          weapon: "Sword and Claws",
          special: "100 Slashes",
          personality: "Still",
          actionshot: "Claw Strike",
          actionshotlink:
            "https://godsvmen.com/swordsayers/img/BastionVFara.png",
          bio: "https://godsvmen.com/characters/bastion.html",
          gallery: "333",
          filter: "kreis sold",
        },
        {
          name: "Ignis",
          fullname: "Ignis Weber",
          img: "https://godsvmen.com/img/char/ignis_gvm_char.png",
          house: "Weber",
          cityname: "Lore, Lords",
          city: "https://godsvmen.com/assets/lore-GVM.png",
          job: "The Weber Prince",
          style: "Devil Fists",
          weapon: "Hand of Hell",
          weaponshot: "",
          special: "Morne",
          personality: "Calculating",
          actionshot: "Demonic Punch",
          actionshotlink:
            "https://godsvmen.com/swordsayers/img/IgnisVStormheart.png",
          bio: "https://godsvmen.com/characters/ignis.html",
          gallery: "155",
          filter: "lords",
        },
        {
          name: "Maxither",
          fullname: "Maxither",
          img: "https://godsvmen.com/img/char/maxither_gvm_char.png",
          house: "Hanor",
          cityname: "Hanor, Heaven's Edge",
          city: "https://godsvmen.com/assets/hanor-GVM.png",
          job: "The Chosen God",
          style: "God Fury",
          weapon: "Flame Splitter",
          weaponshot: "",
          special: "God STagger",
          personality: "Confidient",
          actionshot: "Heart of Fury",
          actionshotlink:
            "https://godsvmen.com/swordsayers/img/LarsVMaxither.png",
          bio: "https://godsvmen.com/characters/maxither.html",
          gallery: "14",
          filter: "hanor",
        },
      ])
  })
