angular
  .module("gvmItems", [])
  .controller("GvmGalController", function ($scope) {
    ($scope.gallery = [
      {
        char: "Seth",
        charArtSize: "3",
        charArtYear: "2025",
        charArtName: "seth-loyalty",
        charArtGallery: "porfolioGallery90",
        charArtTitle: "Seth Loyalty",
      },
      {
        char: "Grandle",
        charArtSize: "3",
        charArtYear: "2025",
        charArtName: "shana-grandle-fin",
        charArtGallery: "porfolioGallery90",
        charArtTitle: "Shana Fin 1",
      },
      {
        char: "Ripper",
        charArtSize: "3",
        charArtYear: "2025",
        charArtName: "shana-ripper-fin",
        charArtGallery: "porfolioGallery90",
        charArtTitle: "Shana Fin 2",
      },
      {
        char: "Ripper",
        charArtSize: "3",
        charArtYear: "2025",
        charArtName: "the_ripper_resting",
        charArtGallery: "porfolioGallery90",
        charArtTitle: "The Ripper Resting",
      },
      {
        char: "Shana",
        charArtSize: "3",
        charArtYear: "2025",
        charArtName: "shana_landing",
        charArtGallery: "porfolioGallery90",
        charArtTitle: "Shana Landing",
      },
      {
        char: "Shana",
        charArtSize: "3",
        charArtYear: "2025",
        charArtName: "shana_defeated",
        charArtGallery: "porfolioGallery90",
        charArtTitle: "Shana Defeated",
      },
      {
        char: "Pond",
        charArtSize: "3",
        charArtYear: "2025",
        charArtName: "pond-profile",
        charArtGallery: "porfolioGallery90",
        charArtTitle: "The Young God Pond",
      },
      {
        char: "Shana",
        charArtSize: "3",
        charArtYear: "2025",
        charArtName: "shana_clarity",
        charArtGallery: "porfolioGallery90",
        charArtTitle: "Shana Clarity",
      },
      {
        char: "Ignis",
        charArtSize: "3",
        charArtYear: "2025",
        charArtName: "Ignisback",
        charArtGallery: "porfolioGallery90",
        charArtTitle: "Ignis Back",
      },
      {
        char: "Grandle",
        charArtSize: "3",
        charArtYear: "2025",
        charArtName: "Golden-grandle",
        charArtGallery: "porfolioGallery90",
        charArtTitle: "Golden Grandle",
      },
      {
        char: "Grandle",
        charArtSize: "8",
        charArtYear: "2025",
        charArtName: "grandle-ignis-faceoff-sm",
        charArtGallery: "porfolioGallery90",
        charArtTitle: "Grandle Ignis Faceoff",
      },
      {
        char: "Ignis",
        charArtSize: "5",
        charArtYear: "2025",
        charArtName: "ignis-faceoff-sm",
        charArtGallery: "porfolioGallery90",
        charArtTitle: "Ignis Faceoff",
      },
      {
        char: "Grandle",
        charArtSize: "5",
        charArtYear: "2025",
        charArtName: "grandle-faceoff-sm",
        charArtGallery: "porfolioGallery90",
        charArtTitle: "Grandle Faceoff",
      },
      {
        char: "Samson",
        charArtSize: "3",
        charArtYear: "2025",
        charArtName: "samson-loyalty-sm",
        charArtGallery: "porfolioGallery90",
        charArtTitle: "Samson Loyalty",
      },
      {
        char: "Shana",
        charArtSize: "3",
        charArtYear: "2025",
        charArtName: "shana-loyalty-sm",
        charArtGallery: "porfolioGallery90",
        charArtTitle: "Shana Loyalty",
      },
      {
        char: "Grandle",
        charArtSize: "3",
        charArtYear: "2025",
        charArtName: "grandle-loss-sm",
        charArtGallery: "porfolioGallery90",
        charArtTitle: "Grandle Loss",
      },
      {
        char: "Shana",
        charArtSize: "3",
        charArtYear: "2025",
        charArtName: "shana-cursed-sm.png",
        charArtGallery: "porfolioGallery90",
        charArtTitle: "Shana Cursed",
      },
      {
        char: "Shana",
        charArtSize: "3",
        charArtYear: "2025",
        charArtName: "shana-cursed-sm.png",
        charArtGallery: "porfolioGallery90",
        charArtTitle: "Shana Curse",
      },
      {
        char: "Grandle",
        charArtSize: "3",
        charArtYear: "2025",
        charArtName: "grandle-fist-sm",
        charArtGallery: "porfolioGallery90",
        charArtTitle: "Grandle Fist",
      },
      {
        char: "Yosh",
        charArtSize: "3",
        charArtYear: "2025",
        charArtName: "yosh-kendo-ready-sm",
        charArtGallery: "porfolioGallery90",
        charArtTitle: "Yosh and Kendo",
      },
      {
        char: "Ignis",
        charArtSize: "3",
        charArtYear: "2025",
        charArtName: "ignis-smile-sm",
        charArtGallery: "porfolioGallery90",
        charArtTitle: "Ignis Smiles",
      },
      {
        char: "Ignis",
        charArtSize: "3",
        charArtYear: "2025",
        charArtName: "grandle-intro-sm",
        charArtGallery: "porfolioGallery90",
        charArtTitle: "Enter the Hero",
      },
    ])
  })